drop table BIOMART_STAGE.BIO_ASSAY_ANALYSIS_EQTL;

CREATE TABLE BIOMART_STAGE.BIO_ASSAY_ANALYSIS_EQTL
(
	BIO_ASY_ANALYSIS_EQTL_ID BIGINT,
	BIO_ASSAY_ANALYSIS_ID BIGINT,
	RS_ID NATIONAL CHARACTER VARYING(50),
	GENE CHARACTER VARYING(50),
	P_VALUE_CHAR CHARACTER VARYING(100),
	CIS_TRANS CHARACTER VARYING(10),
	DISTANCE_FROM_GENE CHARACTER VARYING(10),
	ETL_ID BIGINT,
	EXT_DATA CHARACTER VARYING(4000)
)
DISTRIBUTE ON (BIO_ASSAY_ANALYSIS_ID);

drop table BIOMART_STAGE.BIO_ASSAY_ANALYSIS_GWAS;

CREATE TABLE BIOMART_STAGE.BIO_ASSAY_ANALYSIS_GWAS
(
	BIO_ASY_ANALYSIS_GWAS_ID BIGINT,
	BIO_ASSAY_ANALYSIS_ID BIGINT,
	RS_ID NATIONAL CHARACTER VARYING(50),
	P_VALUE_CHAR CHARACTER VARYING(100),
	ETL_ID BIGINT,
	EXT_DATA CHARACTER VARYING(4000)
)
DISTRIBUTE ON (BIO_ASSAY_ANALYSIS_ID);
